const translations={
sv:{
"title.home":"Start | ANKA Tech","title.services":"Tjänster | ANKA Tech","title.partners":"Partners | ANKA Tech","title.assignments":"Uppdrag | ANKA Tech","title.contact":"Kontakt | ANKA Tech",
"nav.home":"Start","nav.services":"Tjänster","nav.partners":"Partners","nav.assignments":"Uppdrag","nav.contact":"Kontakt","nav.cta":"Starta dialog",
"common.readMore":"Läs mer",
"home.kicker":"ANKA Engineering AB / Advanced Vehicle Engineering","home.heroTitle":"Engineering för ADAS, verifiering och tekniska testmiljöer.","home.heroLead":"ANKA Tech hjälper tekniska team från behov och osäkerhet till verifierad lösning. Fokus ligger på produktutveckling, Euro NCAP-relaterad provning, testautomation, mätdata och robusta systemflöden där resultatet måste fungera i verkligheten.","home.primaryCta":"Beskriv uppdraget","home.secondaryCta":"Utforska tjänster","home.metric1":"Scenarier & provflöden","home.metric2":"Positionering & mätdata","home.metric3":"Automation & verifiering","home.whatEyebrow":"Vad ANKA Tech gör","home.whatTitle":"Bygger tekniska lösningar nära test, data och verklig användning.","home.whatText":"Sidan signalerar snabbt vad bolaget kan hjälpa till med: utveckling av testnära verktyg, felsökning i komplexa miljöer och verifiering där precision, repeterbarhet och spårbarhet är centralt.","home.card1Title":"Produktutveckling","home.card1Text":"Testnära produkter, verktyg, plattformar och integrationslösningar för moderna engineeringteam.","home.card2Title":"Problemlösning och expertstöd","home.card2Text":"Teknisk analys, felsökning och riktade insatser när system, testmiljö eller dataflöde måste stabiliseras.","home.card3Title":"Test och verifiering","home.card3Text":"ADAS, Euro NCAP-relevanta flöden, HIL, GNSS/INS och automatiserad datainsamling.","home.processTitle":"Från teknisk utmaning till verifierad lösning.","home.process1Title":"Förstå miljön","home.process1Text":"System, begränsningar, dataflöden, utrustning och kravbild kartläggs.","home.process2Title":"Bygga lösningen","home.process2Text":"Verktyg, integrationer eller testflöden utvecklas nära den verkliga användningen.","home.process3Title":"Verifiera resultatet","home.process3Text":"Leveransen testas, dokumenteras och görs praktiskt användbar för teamet.","home.ecosystemEyebrow":"Tekniskt sammanhang","home.ecosystemTitle":"Verksam i ett etablerat engineering- och testlandskap.","home.nextEyebrow":"Nästa steg","home.nextTitle":"Har ni ett provflöde, systemproblem eller utvecklingsbehov som kräver tekniskt genomförande?","home.nextCta":"Starta dialog",
"services.eyebrow":"Tjänster","services.title":"Engineeringstöd för avancerade fordons- och testmiljöer.","services.lead":"ANKA Tech fokuserar på praktisk produktutveckling, problemlösning och verifiering i miljöer där flera system ska fungera tillsammans.","services.s1Title":"Produktutveckling","services.s1Text":"Utveckling av testnära produkter, verktyg, plattformar och integrationslösningar för moderna engineeringteam.","services.s1Li1":"Testgeneratorer och dataverktyg","services.s1Li2":"Integration mot mätutrustning, fordon och analysmiljöer","services.s1Li3":"Prototyp, implementation, test och överlämning","services.s2Title":"Problemlösning och expertstöd","services.s2Text":"Teknisk analys, felsökning, systemförståelse och riktade insatser i komplexa miljöer där kvalitet och takt är avgörande.","services.s2Li1":"Felsökning av testflöden och datakedjor","services.s2Li2":"Teknisk rådgivning kring metod och verktyg","services.s2Li3":"Stöd vid kritiska leveranser och flaskhalsar","services.s3Title":"Test och verifiering","services.s3Text":"ADAS, Euro NCAP-relevanta flöden, HIL, GNSS/INS, automatiserad testning och spårbar datainsamling.","services.s3Li1":"Scenariostöd, testplanering och körfiler","services.s3Li2":"Automatiserad insamling och analys","services.s3Li3":"Verifiering i labb, bana och fordonsnära miljöer","services.breadthEyebrow":"Teknisk bredd","services.breadthTitle":"Kompetens där hårdvara, mjukvara och data möts.",
"partners.eyebrow":"Partners","partners.title":"Ett tekniskt ekosystem kring provning, mätning och fordonsutveckling.","partners.lead":"ANKA Tech presenteras med en seriös logovägg och en ren layout som stärker trovärdighet utan att överdriva budskapet.","partners.valueEyebrow":"Samarbetsvärde","partners.valueTitle":"Rätt miljö, rätt data och rätt teknisk metod.","partners.valueText":"Avancerad provning kräver kontroll över utrustning, testflöden, scenarier, data och praktiska begränsningar. ANKA Tech bidrar med engineeringstöd som knyter ihop delarna till användbara resultat.",
"assign.eyebrow":"Uppdrag","assign.title":"För uppdragsgivare, engineeringteam och tekniska specialister.","assign.lead":"ANKA Tech kan gå in som specialist, utvecklingsresurs eller teknisk problemlösare i uppdrag där genomförande och resultat väger tyngre än presentationer.","assign.c1Title":"Uppdragsgivare","assign.c1Text":"Stöd vid ADAS-provning, testautomation, integration, mätdata och verifiering.","assign.c2Title":"Engineeringteam","assign.c2Text":"Praktisk hjälp i testmiljöer, systemflöden och tekniska problem som behöver lösas.","assign.c3Title":"Uppdragstagare","assign.c3Text":"Kontaktväg för tekniska profiler inom fordon, provning, automation och dataanalys.","assign.formEyebrow":"Uppdragsform","assign.formTitle":"Flexibelt stöd efter behov.","assign.p1Title":"Specialistinsats","assign.p1Text":"Riktad insats för en teknisk fråga, integration eller leverans.","assign.p2Title":"Projektstöd","assign.p2Text":"Kontinuerlig förstärkning tillsammans med kundens engineeringteam.","assign.p3Title":"Utvecklingspaket","assign.p3Text":"Framtagning av ett verktyg, flöde eller teknisk lösning med tydlig leverans.","assign.nextEyebrow":"Starta uppdrag","assign.nextTitle":"Beskriv behovet, miljön eller den tekniska utmaningen.","assign.nextCta":"Gå till kontakt",
"contact.eyebrow":"Kontakt","contact.title":"Starta en teknisk dialog.","contact.lead":"Beskriv uppdraget, systemmiljön eller frågan. Formuläret är byggt för både uppdragsgivare och uppdragstagare.","contact.asideTitle":"Snabbare svar med rätt underlag","contact.asideText":"Ange gärna systemtyp, testmiljö, tidsplan, verktyg, datakällor och vad som behöver verifieras eller lösas.","contact.fitTitle":"Passar särskilt bra för","contact.fit1":"ADAS- och Euro NCAP-relaterade flöden","contact.fit2":"Testautomation och datainsamling","contact.fit3":"GNSS/INS och mätdata","contact.fit4":"Produktutveckling nära teknisk provning",
"form.role":"Kontaktroll","form.chooseRole":"Välj roll","form.contractor":"Uppdragstagare","form.client":"Uppdragsgivare","form.name":"Namn","form.phone":"Telefonnummer","form.email":"E-post","form.company":"Bolag / organisation","form.address":"Adress","form.attachment":"Bilaga / CV","form.message":"Meddelande","form.messagePlaceholder":"Beskriv uppdraget, testmiljön, tidsplanen eller vilken typ av stöd du söker.","form.consent":"Jag samtycker till att ANKA Engineering AB behandlar mina uppgifter för att kunna återkomma i ärendet.","form.submit":"Skicka förfrågan","form.note":"Byt ut REPLACE_WITH_YOUR_EMAIL mot mottagarens e-postadress innan publicering.",
"footer.description":"Produktutveckling, teknisk problemlösning och verifiering för avancerade fordonsmiljöer.","footer.pages":"Sidor","footer.focusTitle":"Fokus","footer.company":"Bolag","footer.brand":"Varumärke: ANKA Tech","footer.contact":"Kontakta oss","footer.bottom":"Teknisk konsultverksamhet med fokus på robusta testmiljöer."
},
en:{
"title.home":"Home | ANKA Tech","title.services":"Services | ANKA Tech","title.partners":"Partners | ANKA Tech","title.assignments":"Assignments | ANKA Tech","title.contact":"Contact | ANKA Tech",
"nav.home":"Home","nav.services":"Services","nav.partners":"Partners","nav.assignments":"Assignments","nav.contact":"Contact","nav.cta":"Start a dialogue",
"common.readMore":"Read more",
"home.kicker":"ANKA Engineering AB / Advanced Vehicle Engineering","home.heroTitle":"Engineering for ADAS, verification and technical test environments.","home.heroLead":"ANKA Tech supports technical teams from need and uncertainty to verified solution. The focus is product development, Euro NCAP-related testing, test automation, measurement data and robust system flows where the result must work in real conditions.","home.primaryCta":"Describe the assignment","home.secondaryCta":"Explore services","home.metric1":"Scenarios & test flows","home.metric2":"Positioning & measurement data","home.metric3":"Automation & verification","home.whatEyebrow":"What ANKA Tech does","home.whatTitle":"Building technical solutions close to testing, data and real-world use.","home.whatText":"The site quickly communicates what the company can support with: development of test-oriented tools, troubleshooting in complex environments and verification where precision, repeatability and traceability are central.","home.card1Title":"Product development","home.card1Text":"Test-oriented products, tools, platforms and integration solutions for modern engineering teams.","home.card2Title":"Problem solving and expert support","home.card2Text":"Technical analysis, troubleshooting and targeted support when a system, test environment or data flow needs to be stabilised.","home.card3Title":"Testing and verification","home.card3Text":"ADAS, Euro NCAP-relevant flows, HIL, GNSS/INS and automated data acquisition.","home.processTitle":"From technical challenge to verified solution.","home.process1Title":"Understand the environment","home.process1Text":"Systems, constraints, data flows, equipment and requirements are mapped.","home.process2Title":"Build the solution","home.process2Text":"Tools, integrations or test flows are developed close to real use.","home.process3Title":"Verify the result","home.process3Text":"The delivery is tested, documented and made practically useful for the team.","home.ecosystemEyebrow":"Technical context","home.ecosystemTitle":"Operating in an established engineering and testing landscape.","home.nextEyebrow":"Next step","home.nextTitle":"Do you have a test flow, system issue or development need that requires technical execution?","home.nextCta":"Start a dialogue",
"services.eyebrow":"Services","services.title":"Engineering support for advanced vehicle and test environments.","services.lead":"ANKA Tech focuses on practical product development, problem solving and verification in environments where multiple systems must work together.","services.s1Title":"Product development","services.s1Text":"Development of test-oriented products, tools, platforms and integration solutions for modern engineering teams.","services.s1Li1":"Test generators and data tools","services.s1Li2":"Integration with measurement equipment, vehicles and analysis environments","services.s1Li3":"Prototype, implementation, testing and handover","services.s2Title":"Problem solving and expert support","services.s2Text":"Technical analysis, troubleshooting, system understanding and targeted support in complex environments where quality and pace matter.","services.s2Li1":"Troubleshooting of test flows and data chains","services.s2Li2":"Technical guidance on methods and tools","services.s2Li3":"Support for critical deliveries and bottlenecks","services.s3Title":"Testing and verification","services.s3Text":"ADAS, Euro NCAP-relevant flows, HIL, GNSS/INS, automated testing and traceable data acquisition.","services.s3Li1":"Scenario support, test planning and drive files","services.s3Li2":"Automated acquisition and analysis","services.s3Li3":"Verification in lab, track and vehicle-adjacent environments","services.breadthEyebrow":"Technical breadth","services.breadthTitle":"Competence where hardware, software and data meet.",
"partners.eyebrow":"Partners","partners.title":"A technical ecosystem around testing, measurement and vehicle development.","partners.lead":"ANKA Tech is presented with a serious logo wall and a clean layout that strengthens credibility without overstatement.","partners.valueEyebrow":"Collaboration value","partners.valueTitle":"The right environment, the right data and the right technical method.","partners.valueText":"Advanced testing requires control over equipment, test flows, scenarios, data and practical constraints. ANKA Tech provides engineering support that connects these parts into useful results.",
"assign.eyebrow":"Assignments","assign.title":"For clients, engineering teams and technical specialists.","assign.lead":"ANKA Tech can contribute as a specialist, development resource or technical problem solver in assignments where execution and results matter more than presentations.","assign.c1Title":"Clients","assign.c1Text":"Support for ADAS testing, test automation, integration, measurement data and verification.","assign.c2Title":"Engineering teams","assign.c2Text":"Practical support in test environments, system flows and technical problems that need to be solved.","assign.c3Title":"Contractors","assign.c3Text":"A contact route for technical profiles in vehicles, testing, automation and data analysis.","assign.formEyebrow":"Assignment format","assign.formTitle":"Flexible support based on need.","assign.p1Title":"Specialist support","assign.p1Text":"A focused effort for a technical question, integration or delivery.","assign.p2Title":"Project support","assign.p2Text":"Continuous reinforcement together with the customer’s engineering team.","assign.p3Title":"Development package","assign.p3Text":"Development of a tool, flow or technical solution with a clear delivery.","assign.nextEyebrow":"Start an assignment","assign.nextTitle":"Describe the need, environment or technical challenge.","assign.nextCta":"Go to contact",
"contact.eyebrow":"Contact","contact.title":"Start a technical dialogue.","contact.lead":"Describe the assignment, system environment or question. The form is designed for both clients and contractors.","contact.asideTitle":"Faster response with the right context","contact.asideText":"Please include system type, test environment, timeline, tools, data sources and what needs to be verified or solved.","contact.fitTitle":"Especially relevant for","contact.fit1":"ADAS and Euro NCAP-related flows","contact.fit2":"Test automation and data acquisition","contact.fit3":"GNSS/INS and measurement data","contact.fit4":"Product development close to technical testing",
"form.role":"Contact role","form.chooseRole":"Select role","form.contractor":"Contractor","form.client":"Client","form.name":"Name","form.phone":"Phone number","form.email":"Email","form.company":"Company / organisation","form.address":"Address","form.attachment":"Attachment / CV","form.message":"Message","form.messagePlaceholder":"Describe the assignment, test environment, timeline or what type of support you need.","form.consent":"I consent to ANKA Engineering AB processing my information in order to respond to this matter.","form.submit":"Send request","form.note":"Replace REPLACE_WITH_YOUR_EMAIL with the recipient email address before publishing.",
"footer.description":"Product development, technical problem solving and verification for advanced vehicle environments.","footer.pages":"Pages","footer.focusTitle":"Focus","footer.company":"Company","footer.brand":"Brand: ANKA Tech","footer.contact":"Contact us","footer.bottom":"Technical consultancy focused on robust test environments."
}}
function applyLang(lang){const dict=translations[lang]||translations.sv;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key]) el.textContent=dict[key]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(dict[key]) el.placeholder=dict[key]});document.querySelectorAll('[data-i18n-title]').forEach(el=>{const key=el.dataset.i18nTitle;if(dict[key]) document.title=dict[key]});document.querySelectorAll('[data-set-lang]').forEach(btn=>btn.classList.toggle('active', btn.dataset.setLang===lang));localStorage.setItem('ankaLang',lang)}
const saved=localStorage.getItem('ankaLang')||'sv';applyLang(saved);document.querySelectorAll('[data-set-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLang(btn.dataset.setLang)));
const menuButton=document.querySelector('.menu-button');const nav=document.querySelector('.site-nav');if(menuButton&&nav){menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))})}document.querySelectorAll('.site-nav a').forEach(a=>a.addEventListener('click',()=>nav?.classList.remove('open')));const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')})},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('.magnetic').forEach(btn=>{btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();const x=e.clientX-r.left-r.width/2;const y=e.clientY-r.top-r.height/2;btn.style.transform=`translate(${x*.08}px, ${y*.12}px)`});btn.addEventListener('mouseleave',()=>{btn.style.transform=''})});
const canvas=document.getElementById('tech-canvas');const ctx=canvas?.getContext('2d');let points=[];function resizeCanvas(){if(!canvas||!ctx)return;canvas.width=window.innerWidth*devicePixelRatio;canvas.height=window.innerHeight*devicePixelRatio;canvas.style.width=window.innerWidth+'px';canvas.style.height=window.innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const count=Math.min(72,Math.floor(window.innerWidth/18));points=Array.from({length:count},()=>({x:Math.random()*window.innerWidth,y:Math.random()*window.innerHeight,vx:(Math.random()-.5)*.28,vy:(Math.random()-.5)*.28}))}function animateCanvas(){if(!canvas||!ctx)return;ctx.clearRect(0,0,window.innerWidth,window.innerHeight);points.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>window.innerWidth)p.vx*=-1;if(p.y<0||p.y>window.innerHeight)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,1.4,0,Math.PI*2);ctx.fillStyle='rgba(27,124,131,.32)';ctx.fill();for(let j=i+1;j<points.length;j++){const q=points[j],dx=p.x-q.x,dy=p.y-q.y,d=Math.sqrt(dx*dx+dy*dy);if(d<130){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=`rgba(27,124,131,${(1-d/130)*.11})`;ctx.lineWidth=1;ctx.stroke()}}});requestAnimationFrame(animateCanvas)}resizeCanvas();animateCanvas();window.addEventListener('resize',resizeCanvas);

// HEADER_HIDE_ON_SCROLL_FIX
const siteHeader = document.querySelector('.site-header');
let lastScrollY = window.scrollY;
let tickingHeader = false;

function updateHeaderOnScroll() {
  if (!siteHeader) return;

  const currentY = window.scrollY;
  const scrollingDown = currentY > lastScrollY;
  const distance = Math.abs(currentY - lastScrollY);

  siteHeader.classList.toggle('header-scrolled', currentY > 24);

  // Keep header visible close to the top.
  if (currentY < 80) {
    siteHeader.classList.remove('header-hidden');
    siteHeader.classList.add('header-visible');
  } else if (distance > 6) {
    if (scrollingDown) {
      siteHeader.classList.add('header-hidden');
      siteHeader.classList.remove('header-visible');
      nav?.classList.remove('open');
      menuButton?.setAttribute('aria-expanded', 'false');
    } else {
      siteHeader.classList.remove('header-hidden');
      siteHeader.classList.add('header-visible');
    }
  }

  lastScrollY = currentY;
  tickingHeader = false;
}

window.addEventListener('scroll', () => {
  if (!tickingHeader) {
    window.requestAnimationFrame(updateHeaderOnScroll);
    tickingHeader = true;
  }
}, { passive: true });

siteHeader?.classList.add('header-visible');
